CREATE DATABASE trackstar_dev;

CREATE USER 'trackstar'@'%' IDENTIFIED BY  '';

GRANT USAGE ON * . * TO  'trackstar'@'%' IDENTIFIED BY  '' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON  `trackstar_dev` . * TO  'trackstar'@'%';

CREATE USER 'trackstar'@'localhost' IDENTIFIED BY  '***';

GRANT ALL PRIVILEGES ON * . * TO  'trackstar'@'localhost' IDENTIFIED BY  '***' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON  `trackstar\_%` . * TO  'trackstar'@'localhost';
